/********************************************************************************
** Form generated from reading UI file 'form_main.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FORM_MAIN_H
#define UI_FORM_MAIN_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form_Main
{
public:
    QAction *actionCa_m_i;
    QAction *actionKetnoi;
    QAction *actionServer;
    QAction *actionTheo_Ca;
    QAction *actionTheo_ng_y;
    QAction *actionTheo_th_ng;
    QAction *actionPh_n_m_m;
    QAction *actionHDSD;
    QAction *action_dulieu_dangky;
    QAction *action_dulieu_hientai;
    QAction *action_dulieu_login;
    QWidget *centralwidget;
    QLineEdit *lineEdit;
    QPushButton *main_btn_exit_2;
    QLabel *label_3;
    QGroupBox *groupBox_7;
    QPushButton *xera_btn_print;
    QPushButton *xera_btn_readagain;
    QPushButton *xera_btn_open;
    QPushButton *xera_btn_closed;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_49;
    QLabel *label_70;
    QLineEdit *xera_text_time_out;
    QLineEdit *xera_text_thanhtien;
    QLineEdit *xera_text_time_sd;
    QLineEdit *xera_text_dongia;
    QLabel *label_50;
    QLabel *label_71;
    QLabel *label_46;
    QLabel *xera_cam_truoc;
    QLabel *label_4;
    QLabel *xevao_cam_truoc;
    QLabel *xera_cam_sau;
    QLabel *xera_anh_cu_sau;
    QLabel *xevao_cam_sau;
    QLabel *xevao_anh_sau;
    QLabel *label_26;
    QLabel *label_5;
    QLabel *label_9;
    QLabel *label_29;
    QLabel *label_27;
    QPushButton *main_btn_history_2;
    QGroupBox *groupBox_4;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLineEdit *xevao_text_bks;
    QLineEdit *xevao_text_tenkh;
    QLineEdit *xevao_text_diachi;
    QLineEdit *xevao_text_sothe;
    QLineEdit *xevao_text_loaixe;
    QLineEdit *xevao_text_time;
    QLabel *label_72;
    QLineEdit *xevao_text_loaive;
    QGroupBox *groupBox_5;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLineEdit *xera_text_time_in;
    QLineEdit *xera_text_sothe;
    QLineEdit *xera_text_loaixe;
    QLineEdit *xera_text_tenkh;
    QLineEdit *xera_text_bks;
    QLineEdit *xera_text_diachi;
    QLineEdit *xera_text_loaive;
    QLabel *label_73;
    QLabel *xevao_anh_truoc;
    QLabel *label_63;
    QLabel *label_2;
    QGroupBox *groupBox;
    QTextEdit *xevao_text_thongbao;
    QGroupBox *groupBox_2;
    QTextEdit *xera_text_thongbao;
    QLabel *label_64;
    QGroupBox *groupBox_6;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *xera_anh_bks_cu;
    QLabel *xera_anh_bks;
    QLabel *xera_anh_sau;
    QLabel *xera_anh_cu_truoc;
    QLabel *label;
    QLabel *lable_status;
    QPushButton *main_btn_setting_2;
    QPushButton *main_btn_history;
    QLabel *label_68;
    QLabel *xera_anh_truoc;
    QPushButton *main_btn_exit;
    QGroupBox *groupBox_3;
    QPushButton *xevao_btn_closed;
    QPushButton *xevao_btn_print;
    QPushButton *xevao_btn_readagain;
    QPushButton *xevao_btn_open;
    QLabel *label_69;
    QLabel *xevao_anh_bks;
    QMenuBar *menubar;
    QMenu *menuFile;
    QMenu *menuC_i_t;
    QMenu *menuB_o_c_o;
    QMenu *menuTh_ng_tin;
    QMenu *menuD_li_u;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *Form_Main)
    {
        if (Form_Main->objectName().isEmpty())
            Form_Main->setObjectName(QString::fromUtf8("Form_Main"));
        Form_Main->setWindowModality(Qt::NonModal);
        Form_Main->resize(1275, 678);
        Form_Main->setMinimumSize(QSize(0, 0));
        QFont font;
        font.setFamily(QString::fromUtf8("Times New Roman"));
        Form_Main->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/rec/pic/form_main.ico"), QSize(), QIcon::Normal, QIcon::Off);
        Form_Main->setWindowIcon(icon);
        Form_Main->setIconSize(QSize(30, 30));
        actionCa_m_i = new QAction(Form_Main);
        actionCa_m_i->setObjectName(QString::fromUtf8("actionCa_m_i"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/rec/pic/data_add.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCa_m_i->setIcon(icon1);
        actionKetnoi = new QAction(Form_Main);
        actionKetnoi->setObjectName(QString::fromUtf8("actionKetnoi"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/rec/pic/setting.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionKetnoi->setIcon(icon2);
        actionServer = new QAction(Form_Main);
        actionServer->setObjectName(QString::fromUtf8("actionServer"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/rec/pic/setting_server.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        actionServer->setIcon(icon3);
        actionTheo_Ca = new QAction(Form_Main);
        actionTheo_Ca->setObjectName(QString::fromUtf8("actionTheo_Ca"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/rec/pic/report.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTheo_Ca->setIcon(icon4);
        actionTheo_ng_y = new QAction(Form_Main);
        actionTheo_ng_y->setObjectName(QString::fromUtf8("actionTheo_ng_y"));
        actionTheo_ng_y->setIcon(icon4);
        actionTheo_th_ng = new QAction(Form_Main);
        actionTheo_th_ng->setObjectName(QString::fromUtf8("actionTheo_th_ng"));
        actionTheo_th_ng->setIcon(icon4);
        actionPh_n_m_m = new QAction(Form_Main);
        actionPh_n_m_m->setObjectName(QString::fromUtf8("actionPh_n_m_m"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/rec/pic/info.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        actionPh_n_m_m->setIcon(icon5);
        actionHDSD = new QAction(Form_Main);
        actionHDSD->setObjectName(QString::fromUtf8("actionHDSD"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/rec/pic/hdsd.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionHDSD->setIcon(icon6);
        action_dulieu_dangky = new QAction(Form_Main);
        action_dulieu_dangky->setObjectName(QString::fromUtf8("action_dulieu_dangky"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/rec/pic/data.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_dulieu_dangky->setIcon(icon7);
        action_dulieu_hientai = new QAction(Form_Main);
        action_dulieu_hientai->setObjectName(QString::fromUtf8("action_dulieu_hientai"));
        action_dulieu_hientai->setIcon(icon7);
        action_dulieu_login = new QAction(Form_Main);
        action_dulieu_login->setObjectName(QString::fromUtf8("action_dulieu_login"));
        action_dulieu_login->setIcon(icon7);
        centralwidget = new QWidget(Form_Main);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        lineEdit = new QLineEdit(centralwidget);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(510, 10, 2, 600));
        lineEdit->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        main_btn_exit_2 = new QPushButton(centralwidget);
        main_btn_exit_2->setObjectName(QString::fromUtf8("main_btn_exit_2"));
        main_btn_exit_2->setGeometry(QRect(4275, 1775, 121, 41));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(90, 180, 71, 21));
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(770, 350, 251, 171));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Times New Roman"));
        font1.setBold(true);
        font1.setWeight(75);
        groupBox_7->setFont(font1);
        groupBox_7->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        xera_btn_print = new QPushButton(groupBox_7);
        xera_btn_print->setObjectName(QString::fromUtf8("xera_btn_print"));
        xera_btn_print->setGeometry(QRect(130, 140, 65, 21));
        QFont font2;
        font2.setBold(false);
        font2.setWeight(50);
        xera_btn_print->setFont(font2);
        xera_btn_print->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xera_btn_readagain = new QPushButton(groupBox_7);
        xera_btn_readagain->setObjectName(QString::fromUtf8("xera_btn_readagain"));
        xera_btn_readagain->setGeometry(QRect(130, 110, 65, 21));
        xera_btn_readagain->setFont(font2);
        xera_btn_readagain->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xera_btn_open = new QPushButton(groupBox_7);
        xera_btn_open->setObjectName(QString::fromUtf8("xera_btn_open"));
        xera_btn_open->setGeometry(QRect(20, 110, 65, 21));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(xera_btn_open->sizePolicy().hasHeightForWidth());
        xera_btn_open->setSizePolicy(sizePolicy);
        xera_btn_open->setFont(font2);
        xera_btn_open->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xera_btn_closed = new QPushButton(groupBox_7);
        xera_btn_closed->setObjectName(QString::fromUtf8("xera_btn_closed"));
        xera_btn_closed->setGeometry(QRect(20, 140, 65, 21));
        sizePolicy.setHeightForWidth(xera_btn_closed->sizePolicy().hasHeightForWidth());
        xera_btn_closed->setSizePolicy(sizePolicy);
        xera_btn_closed->setFont(font2);
        xera_btn_closed->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        label_44 = new QLabel(groupBox_7);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 20, 71, 21));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Times New Roman"));
        font3.setBold(false);
        font3.setWeight(50);
        label_44->setFont(font3);
        label_44->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_45 = new QLabel(groupBox_7);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 60, 71, 21));
        label_45->setFont(font3);
        label_45->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_49 = new QLabel(groupBox_7);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(10, 40, 71, 21));
        label_49->setFont(font3);
        label_49->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_70 = new QLabel(groupBox_7);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(10, 80, 71, 21));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Times New Roman"));
        font4.setPointSize(8);
        font4.setBold(false);
        font4.setWeight(50);
        label_70->setFont(font4);
        label_70->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        xera_text_time_out = new QLineEdit(groupBox_7);
        xera_text_time_out->setObjectName(QString::fromUtf8("xera_text_time_out"));
        xera_text_time_out->setGeometry(QRect(80, 20, 161, 21));
        xera_text_time_out->setFont(font);
        xera_text_time_out->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xera_text_thanhtien = new QLineEdit(groupBox_7);
        xera_text_thanhtien->setObjectName(QString::fromUtf8("xera_text_thanhtien"));
        xera_text_thanhtien->setGeometry(QRect(80, 60, 131, 21));
        xera_text_thanhtien->setFont(font);
        xera_text_thanhtien->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xera_text_time_sd = new QLineEdit(groupBox_7);
        xera_text_time_sd->setObjectName(QString::fromUtf8("xera_text_time_sd"));
        xera_text_time_sd->setGeometry(QRect(80, 80, 131, 21));
        xera_text_time_sd->setFont(font);
        xera_text_time_sd->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xera_text_dongia = new QLineEdit(groupBox_7);
        xera_text_dongia->setObjectName(QString::fromUtf8("xera_text_dongia"));
        xera_text_dongia->setGeometry(QRect(80, 40, 131, 21));
        xera_text_dongia->setFont(font);
        xera_text_dongia->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        label_50 = new QLabel(groupBox_7);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(210, 40, 31, 21));
        label_50->setFont(font3);
        label_50->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_71 = new QLabel(groupBox_7);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(210, 80, 31, 21));
        label_71->setFont(font3);
        label_71->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_46 = new QLabel(groupBox_7);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(210, 60, 31, 21));
        label_46->setFont(font3);
        label_46->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        xera_cam_truoc = new QLabel(centralwidget);
        xera_cam_truoc->setObjectName(QString::fromUtf8("xera_cam_truoc"));
        xera_cam_truoc->setGeometry(QRect(520, 30, 241, 150));
        xera_cam_truoc->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_cam_truoc->setScaledContents(true);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(340, 180, 91, 21));
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        xevao_cam_truoc = new QLabel(centralwidget);
        xevao_cam_truoc->setObjectName(QString::fromUtf8("xevao_cam_truoc"));
        xevao_cam_truoc->setGeometry(QRect(10, 30, 241, 150));
        xevao_cam_truoc->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xevao_cam_truoc->setScaledContents(true);
        xera_cam_sau = new QLabel(centralwidget);
        xera_cam_sau->setObjectName(QString::fromUtf8("xera_cam_sau"));
        xera_cam_sau->setGeometry(QRect(520, 200, 241, 150));
        xera_cam_sau->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_cam_sau->setScaledContents(true);
        xera_anh_cu_sau = new QLabel(centralwidget);
        xera_anh_cu_sau->setObjectName(QString::fromUtf8("xera_anh_cu_sau"));
        xera_anh_cu_sau->setGeometry(QRect(1020, 200, 241, 150));
        xera_anh_cu_sau->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_cu_sau->setScaledContents(true);
        xevao_cam_sau = new QLabel(centralwidget);
        xevao_cam_sau->setObjectName(QString::fromUtf8("xevao_cam_sau"));
        xevao_cam_sau->setGeometry(QRect(10, 200, 241, 150));
        xevao_cam_sau->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xevao_cam_sau->setScaledContents(true);
        xevao_anh_sau = new QLabel(centralwidget);
        xevao_anh_sau->setObjectName(QString::fromUtf8("xevao_anh_sau"));
        xevao_anh_sau->setGeometry(QRect(260, 200, 241, 150));
        xevao_anh_sau->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xevao_anh_sau->setScaledContents(true);
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(610, 180, 71, 21));
        label_26->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(340, 0, 111, 41));
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(850, 10, 91, 21));
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(1080, 10, 111, 21));
        label_29->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(850, 180, 101, 20));
        label_27->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        main_btn_history_2 = new QPushButton(centralwidget);
        main_btn_history_2->setObjectName(QString::fromUtf8("main_btn_history_2"));
        main_btn_history_2->setGeometry(QRect(3990, 1775, 121, 41));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 350, 241, 171));
        groupBox_4->setFont(font1);
        groupBox_4->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        label_51 = new QLabel(groupBox_4);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 20, 61, 21));
        label_51->setFont(font4);
        label_51->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_52 = new QLabel(groupBox_4);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 60, 61, 21));
        label_52->setFont(font4);
        label_52->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_53 = new QLabel(groupBox_4);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 80, 61, 21));
        label_53->setFont(font4);
        label_53->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_54 = new QLabel(groupBox_4);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 100, 61, 21));
        label_54->setFont(font4);
        label_54->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_55 = new QLabel(groupBox_4);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 120, 61, 21));
        label_55->setFont(font4);
        label_55->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_56 = new QLabel(groupBox_4);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 40, 61, 21));
        label_56->setFont(font4);
        label_56->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        xevao_text_bks = new QLineEdit(groupBox_4);
        xevao_text_bks->setObjectName(QString::fromUtf8("xevao_text_bks"));
        xevao_text_bks->setGeometry(QRect(70, 40, 161, 21));
        xevao_text_bks->setFont(font);
        xevao_text_bks->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xevao_text_tenkh = new QLineEdit(groupBox_4);
        xevao_text_tenkh->setObjectName(QString::fromUtf8("xevao_text_tenkh"));
        xevao_text_tenkh->setGeometry(QRect(70, 80, 161, 21));
        xevao_text_tenkh->setFont(font);
        xevao_text_tenkh->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xevao_text_diachi = new QLineEdit(groupBox_4);
        xevao_text_diachi->setObjectName(QString::fromUtf8("xevao_text_diachi"));
        xevao_text_diachi->setGeometry(QRect(70, 120, 161, 21));
        xevao_text_diachi->setFont(font);
        xevao_text_diachi->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xevao_text_sothe = new QLineEdit(groupBox_4);
        xevao_text_sothe->setObjectName(QString::fromUtf8("xevao_text_sothe"));
        xevao_text_sothe->setGeometry(QRect(70, 60, 161, 21));
        xevao_text_sothe->setFont(font1);
        xevao_text_sothe->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xevao_text_loaixe = new QLineEdit(groupBox_4);
        xevao_text_loaixe->setObjectName(QString::fromUtf8("xevao_text_loaixe"));
        xevao_text_loaixe->setGeometry(QRect(70, 100, 161, 21));
        xevao_text_loaixe->setFont(font);
        xevao_text_loaixe->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xevao_text_time = new QLineEdit(groupBox_4);
        xevao_text_time->setObjectName(QString::fromUtf8("xevao_text_time"));
        xevao_text_time->setGeometry(QRect(70, 20, 161, 21));
        xevao_text_time->setFont(font);
        xevao_text_time->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        label_72 = new QLabel(groupBox_4);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(10, 140, 61, 21));
        label_72->setFont(font4);
        label_72->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        xevao_text_loaive = new QLineEdit(groupBox_4);
        xevao_text_loaive->setObjectName(QString::fromUtf8("xevao_text_loaive"));
        xevao_text_loaive->setGeometry(QRect(70, 140, 161, 21));
        xevao_text_loaive->setFont(font);
        xevao_text_loaive->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(520, 350, 251, 171));
        groupBox_5->setFont(font1);
        groupBox_5->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        label_57 = new QLabel(groupBox_5);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(10, 20, 71, 21));
        label_57->setFont(font4);
        label_57->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_58 = new QLabel(groupBox_5);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 60, 71, 21));
        label_58->setFont(font4);
        label_58->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_59 = new QLabel(groupBox_5);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(10, 80, 71, 21));
        label_59->setFont(font3);
        label_59->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_60 = new QLabel(groupBox_5);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(10, 100, 71, 21));
        label_60->setFont(font4);
        label_60->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        label_61 = new QLabel(groupBox_5);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(10, 120, 71, 21));
        label_61->setFont(font4);
        label_61->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        label_62 = new QLabel(groupBox_5);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 40, 71, 21));
        label_62->setFont(font4);
        label_62->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 127);"));
        xera_text_time_in = new QLineEdit(groupBox_5);
        xera_text_time_in->setObjectName(QString::fromUtf8("xera_text_time_in"));
        xera_text_time_in->setGeometry(QRect(80, 20, 161, 21));
        xera_text_time_in->setFont(font);
        xera_text_time_in->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xera_text_sothe = new QLineEdit(groupBox_5);
        xera_text_sothe->setObjectName(QString::fromUtf8("xera_text_sothe"));
        xera_text_sothe->setGeometry(QRect(80, 60, 161, 21));
        xera_text_sothe->setFont(font);
        xera_text_sothe->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xera_text_loaixe = new QLineEdit(groupBox_5);
        xera_text_loaixe->setObjectName(QString::fromUtf8("xera_text_loaixe"));
        xera_text_loaixe->setGeometry(QRect(80, 100, 161, 21));
        xera_text_loaixe->setFont(font);
        xera_text_loaixe->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        xera_text_tenkh = new QLineEdit(groupBox_5);
        xera_text_tenkh->setObjectName(QString::fromUtf8("xera_text_tenkh"));
        xera_text_tenkh->setGeometry(QRect(80, 80, 161, 21));
        xera_text_tenkh->setFont(font);
        xera_text_tenkh->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xera_text_bks = new QLineEdit(groupBox_5);
        xera_text_bks->setObjectName(QString::fromUtf8("xera_text_bks"));
        xera_text_bks->setGeometry(QRect(80, 40, 161, 21));
        xera_text_bks->setFont(font);
        xera_text_bks->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xera_text_diachi = new QLineEdit(groupBox_5);
        xera_text_diachi->setObjectName(QString::fromUtf8("xera_text_diachi"));
        xera_text_diachi->setGeometry(QRect(80, 120, 161, 21));
        xera_text_diachi->setFont(font);
        xera_text_diachi->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);"));
        xera_text_loaive = new QLineEdit(groupBox_5);
        xera_text_loaive->setObjectName(QString::fromUtf8("xera_text_loaive"));
        xera_text_loaive->setGeometry(QRect(80, 140, 161, 21));
        xera_text_loaive->setFont(font);
        xera_text_loaive->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);"));
        label_73 = new QLabel(groupBox_5);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(10, 140, 71, 21));
        label_73->setFont(font4);
        label_73->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);"));
        xevao_anh_truoc = new QLabel(centralwidget);
        xevao_anh_truoc->setObjectName(QString::fromUtf8("xevao_anh_truoc"));
        xevao_anh_truoc->setGeometry(QRect(260, 30, 241, 150));
        xevao_anh_truoc->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xevao_anh_truoc->setScaledContents(true);
        label_63 = new QLabel(centralwidget);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(730, 0, 81, 31));
        QFont font5;
        font5.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font5.setPointSize(16);
        font5.setBold(true);
        font5.setWeight(75);
        label_63->setFont(font5);
        label_63->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(80, 0, 81, 41));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 520, 491, 91));
        groupBox->setFont(font1);
        groupBox->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        xevao_text_thongbao = new QTextEdit(groupBox);
        xevao_text_thongbao->setObjectName(QString::fromUtf8("xevao_text_thongbao"));
        xevao_text_thongbao->setGeometry(QRect(10, 20, 481, 71));
        xevao_text_thongbao->setFont(font);
        xevao_text_thongbao->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        xevao_text_thongbao->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(520, 520, 501, 91));
        groupBox_2->setFont(font1);
        groupBox_2->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        xera_text_thongbao = new QTextEdit(groupBox_2);
        xera_text_thongbao->setObjectName(QString::fromUtf8("xera_text_thongbao"));
        xera_text_thongbao->setGeometry(QRect(10, 20, 491, 71));
        xera_text_thongbao->setFont(font);
        xera_text_thongbao->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        xera_text_thongbao->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        label_64 = new QLabel(centralwidget);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(600, 10, 81, 21));
        label_64->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(1020, 350, 241, 201));
        groupBox_6->setFont(font1);
        groupBox_6->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        label_65 = new QLabel(groupBox_6);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(30, 50, 41, 21));
        label_65->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        label_66 = new QLabel(groupBox_6);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(1355, 180, 376, 41));
        label_67 = new QLabel(groupBox_6);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(30, 130, 41, 21));
        label_67->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        xera_anh_bks_cu = new QLabel(groupBox_6);
        xera_anh_bks_cu->setObjectName(QString::fromUtf8("xera_anh_bks_cu"));
        xera_anh_bks_cu->setGeometry(QRect(80, 20, 151, 81));
        xera_anh_bks_cu->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_bks_cu->setScaledContents(true);
        xera_anh_bks = new QLabel(groupBox_6);
        xera_anh_bks->setObjectName(QString::fromUtf8("xera_anh_bks"));
        xera_anh_bks->setGeometry(QRect(80, 110, 151, 81));
        xera_anh_bks->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_bks->setScaledContents(true);
        xera_anh_sau = new QLabel(centralwidget);
        xera_anh_sau->setObjectName(QString::fromUtf8("xera_anh_sau"));
        xera_anh_sau->setGeometry(QRect(770, 200, 241, 150));
        xera_anh_sau->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_sau->setScaledContents(true);
        xera_anh_cu_truoc = new QLabel(centralwidget);
        xera_anh_cu_truoc->setObjectName(QString::fromUtf8("xera_anh_cu_truoc"));
        xera_anh_cu_truoc->setGeometry(QRect(1020, 30, 241, 150));
        xera_anh_cu_truoc->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_cu_truoc->setScaledContents(true);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(220, -10, 121, 51));
        label->setFont(font5);
        label->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        lable_status = new QLabel(centralwidget);
        lable_status->setObjectName(QString::fromUtf8("lable_status"));
        lable_status->setGeometry(QRect(10, 610, 1261, 16));
        lable_status->setFont(font3);
        lable_status->setStyleSheet(QString::fromUtf8("background-color: rgb(70, 141, 211);"));
        main_btn_setting_2 = new QPushButton(centralwidget);
        main_btn_setting_2->setObjectName(QString::fromUtf8("main_btn_setting_2"));
        main_btn_setting_2->setGeometry(QRect(4130, 1775, 121, 41));
        main_btn_history = new QPushButton(centralwidget);
        main_btn_history->setObjectName(QString::fromUtf8("main_btn_history"));
        main_btn_history->setGeometry(QRect(1050, 580, 71, 25));
        QFont font6;
        font6.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font6.setBold(true);
        font6.setWeight(75);
        main_btn_history->setFont(font6);
        main_btn_history->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 255);"));
        label_68 = new QLabel(centralwidget);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(1080, 180, 111, 21));
        label_68->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        xera_anh_truoc = new QLabel(centralwidget);
        xera_anh_truoc->setObjectName(QString::fromUtf8("xera_anh_truoc"));
        xera_anh_truoc->setGeometry(QRect(770, 30, 241, 150));
        xera_anh_truoc->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xera_anh_truoc->setScaledContents(true);
        main_btn_exit = new QPushButton(centralwidget);
        main_btn_exit->setObjectName(QString::fromUtf8("main_btn_exit"));
        main_btn_exit->setGeometry(QRect(1150, 580, 71, 25));
        main_btn_exit->setFont(font6);
        main_btn_exit->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 255);"));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(260, 350, 241, 171));
        groupBox_3->setFont(font1);
        groupBox_3->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 242, 255);"));
        xevao_btn_closed = new QPushButton(groupBox_3);
        xevao_btn_closed->setObjectName(QString::fromUtf8("xevao_btn_closed"));
        xevao_btn_closed->setGeometry(QRect(30, 140, 65, 21));
        sizePolicy.setHeightForWidth(xevao_btn_closed->sizePolicy().hasHeightForWidth());
        xevao_btn_closed->setSizePolicy(sizePolicy);
        xevao_btn_closed->setFont(font2);
        xevao_btn_closed->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xevao_btn_print = new QPushButton(groupBox_3);
        xevao_btn_print->setObjectName(QString::fromUtf8("xevao_btn_print"));
        xevao_btn_print->setGeometry(QRect(160, 140, 65, 21));
        xevao_btn_print->setFont(font2);
        xevao_btn_print->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xevao_btn_readagain = new QPushButton(groupBox_3);
        xevao_btn_readagain->setObjectName(QString::fromUtf8("xevao_btn_readagain"));
        xevao_btn_readagain->setGeometry(QRect(160, 110, 65, 21));
        xevao_btn_readagain->setFont(font2);
        xevao_btn_readagain->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        xevao_btn_open = new QPushButton(groupBox_3);
        xevao_btn_open->setObjectName(QString::fromUtf8("xevao_btn_open"));
        xevao_btn_open->setGeometry(QRect(30, 110, 65, 21));
        sizePolicy.setHeightForWidth(xevao_btn_open->sizePolicy().hasHeightForWidth());
        xevao_btn_open->setSizePolicy(sizePolicy);
        xevao_btn_open->setFont(font2);
        xevao_btn_open->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"));
        label_69 = new QLabel(groupBox_3);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(20, 50, 51, 21));
        label_69->setStyleSheet(QString::fromUtf8("color: rgb(85, 0, 255);"));
        xevao_anh_bks = new QLabel(groupBox_3);
        xevao_anh_bks->setObjectName(QString::fromUtf8("xevao_anh_bks"));
        xevao_anh_bks->setGeometry(QRect(80, 20, 151, 81));
        xevao_anh_bks->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        xevao_anh_bks->setScaledContents(true);
        Form_Main->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Form_Main);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1275, 19));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuC_i_t = new QMenu(menubar);
        menuC_i_t->setObjectName(QString::fromUtf8("menuC_i_t"));
        menuB_o_c_o = new QMenu(menubar);
        menuB_o_c_o->setObjectName(QString::fromUtf8("menuB_o_c_o"));
        menuTh_ng_tin = new QMenu(menubar);
        menuTh_ng_tin->setObjectName(QString::fromUtf8("menuTh_ng_tin"));
        menuD_li_u = new QMenu(menubar);
        menuD_li_u->setObjectName(QString::fromUtf8("menuD_li_u"));
        Form_Main->setMenuBar(menubar);
        statusbar = new QStatusBar(Form_Main);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        Form_Main->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuC_i_t->menuAction());
        menubar->addAction(menuB_o_c_o->menuAction());
        menubar->addAction(menuTh_ng_tin->menuAction());
        menubar->addAction(menuD_li_u->menuAction());
        menuFile->addAction(actionCa_m_i);
        menuC_i_t->addAction(actionKetnoi);
        menuC_i_t->addAction(actionServer);
        menuB_o_c_o->addAction(actionTheo_Ca);
        menuB_o_c_o->addAction(actionTheo_ng_y);
        menuB_o_c_o->addAction(actionTheo_th_ng);
        menuTh_ng_tin->addAction(actionPh_n_m_m);
        menuTh_ng_tin->addAction(actionHDSD);
        menuD_li_u->addAction(action_dulieu_dangky);
        menuD_li_u->addAction(action_dulieu_hientai);
        menuD_li_u->addAction(action_dulieu_login);

        retranslateUi(Form_Main);

        QMetaObject::connectSlotsByName(Form_Main);
    } // setupUi

    void retranslateUi(QMainWindow *Form_Main)
    {
        Form_Main->setWindowTitle(QCoreApplication::translate("Form_Main", "Barie", nullptr));
        actionCa_m_i->setText(QCoreApplication::translate("Form_Main", "Ca m\341\273\233i", nullptr));
        actionKetnoi->setText(QCoreApplication::translate("Form_Main", "K\341\272\277t n\341\273\221i", nullptr));
        actionServer->setText(QCoreApplication::translate("Form_Main", "Server", nullptr));
        actionTheo_Ca->setText(QCoreApplication::translate("Form_Main", "Theo Ca", nullptr));
        actionTheo_ng_y->setText(QCoreApplication::translate("Form_Main", "Theo ng\303\240y", nullptr));
        actionTheo_th_ng->setText(QCoreApplication::translate("Form_Main", "Theo th\303\241ng", nullptr));
        actionPh_n_m_m->setText(QCoreApplication::translate("Form_Main", "Ph\341\272\247n m\341\273\201m", nullptr));
        actionHDSD->setText(QCoreApplication::translate("Form_Main", "HDSD", nullptr));
        action_dulieu_dangky->setText(QCoreApplication::translate("Form_Main", "D\341\273\257 li\341\273\207u \304\221\304\203ng k\303\275", nullptr));
        action_dulieu_hientai->setText(QCoreApplication::translate("Form_Main", "D\341\273\257 li\341\273\207u hi\341\273\207n t\341\272\241i", nullptr));
        action_dulieu_login->setText(QCoreApplication::translate("Form_Main", "D\341\273\257 li\341\273\207u \304\221\304\203ng nh\341\272\255p", nullptr));
        main_btn_exit_2->setText(QCoreApplication::translate("Form_Main", "Tho\303\241t", nullptr));
        label_3->setText(QCoreApplication::translate("Form_Main", "Camera Sau", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("Form_Main", "Thao t\303\241c", nullptr));
        xera_btn_print->setText(QCoreApplication::translate("Form_Main", "In", nullptr));
        xera_btn_readagain->setText(QCoreApplication::translate("Form_Main", "\304\220\341\273\215c BKS", nullptr));
        xera_btn_open->setText(QCoreApplication::translate("Form_Main", "M\341\273\237 c\341\273\225ng", nullptr));
        xera_btn_closed->setText(QCoreApplication::translate("Form_Main", "\304\220\303\263ng c\341\273\225ng", nullptr));
        label_44->setText(QCoreApplication::translate("Form_Main", "Th\341\273\235i gian ra", nullptr));
        label_45->setText(QCoreApplication::translate("Form_Main", "S\341\273\221 ti\341\273\201n", nullptr));
        label_49->setText(QCoreApplication::translate("Form_Main", "\304\220\306\241n gi\303\241", nullptr));
        label_70->setText(QCoreApplication::translate("Form_Main", "<html><head/><body><p>Th\341\273\235i gian SD</p></body></html>", nullptr));
        label_50->setText(QCoreApplication::translate("Form_Main", "(Vn\304\221)", nullptr));
        label_71->setText(QCoreApplication::translate("Form_Main", "(Ph\303\272t)", nullptr));
        label_46->setText(QCoreApplication::translate("Form_Main", "(Vn\304\221)", nullptr));
        xera_cam_truoc->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        label_4->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh camera sau", nullptr));
        xevao_cam_truoc->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xera_cam_sau->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xera_anh_cu_sau->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xevao_cam_sau->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xevao_anh_sau->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        label_26->setText(QCoreApplication::translate("Form_Main", "Camera Sau", nullptr));
        label_5->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh camera tr\306\260\341\273\233c", nullptr));
        label_9->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh camera tr\306\260\341\273\233c", nullptr));
        label_29->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh tr\306\260\341\273\233c( Xe v\303\240o)", nullptr));
        label_27->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh camera sau", nullptr));
        main_btn_history_2->setText(QCoreApplication::translate("Form_Main", "L\341\273\213ch s\341\273\255", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("Form_Main", "Th\303\264ng tin kh\303\241ch", nullptr));
        label_51->setText(QCoreApplication::translate("Form_Main", "Th\341\273\235i gian", nullptr));
        label_52->setText(QCoreApplication::translate("Form_Main", "S\341\273\221 th\341\272\273", nullptr));
        label_53->setText(QCoreApplication::translate("Form_Main", "Kh\303\241ch h\303\240ng", nullptr));
        label_54->setText(QCoreApplication::translate("Form_Main", "Lo\341\272\241i xe", nullptr));
        label_55->setText(QCoreApplication::translate("Form_Main", "\304\220\341\273\213a ch\341\273\211", nullptr));
        label_56->setText(QCoreApplication::translate("Form_Main", "BKS", nullptr));
        label_72->setText(QCoreApplication::translate("Form_Main", "Lo\341\272\241i v\303\251", nullptr));
        xevao_text_loaive->setText(QString());
        groupBox_5->setTitle(QCoreApplication::translate("Form_Main", "Th\303\264ng tin kh\303\241ch", nullptr));
        label_57->setText(QCoreApplication::translate("Form_Main", "Th\341\273\235i gian v\303\240o", nullptr));
        label_58->setText(QCoreApplication::translate("Form_Main", "S\341\273\221 th\341\272\273", nullptr));
        label_59->setText(QCoreApplication::translate("Form_Main", "Kh\303\241ch h\303\240ng", nullptr));
        label_60->setText(QCoreApplication::translate("Form_Main", "Lo\341\272\241i xe", nullptr));
        label_61->setText(QCoreApplication::translate("Form_Main", "\304\220\341\273\213a ch\341\273\211", nullptr));
        label_62->setText(QCoreApplication::translate("Form_Main", "BKS", nullptr));
        label_73->setText(QCoreApplication::translate("Form_Main", "Lo\341\272\241i v\303\251", nullptr));
        xevao_anh_truoc->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        label_63->setText(QCoreApplication::translate("Form_Main", "XE RA", nullptr));
        label_2->setText(QCoreApplication::translate("Form_Main", "Camera Tr\306\260\341\273\233c", nullptr));
        groupBox->setTitle(QCoreApplication::translate("Form_Main", "Th\303\264ng b\303\241o v\303\240o", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("Form_Main", "Th\303\264ng b\303\241o ra", nullptr));
        label_64->setText(QCoreApplication::translate("Form_Main", "Camera Tr\306\260\341\273\233c", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("Form_Main", "So s\303\241nh BKS", nullptr));
        label_65->setText(QCoreApplication::translate("Form_Main", "BKS c\305\251", nullptr));
        label_66->setText(QCoreApplication::translate("Form_Main", "BKS c\305\251", nullptr));
        label_67->setText(QCoreApplication::translate("Form_Main", "BKS m\341\273\233i", nullptr));
        xera_anh_bks_cu->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xera_anh_bks->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xera_anh_sau->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        xera_anh_cu_truoc->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        label->setText(QCoreApplication::translate("Form_Main", "XE V\303\200O", nullptr));
        lable_status->setText(QCoreApplication::translate("Form_Main", "Status", nullptr));
        main_btn_setting_2->setText(QCoreApplication::translate("Form_Main", "C\303\240i \304\221\341\272\267t", nullptr));
        main_btn_history->setText(QCoreApplication::translate("Form_Main", "L\306\260u", nullptr));
        label_68->setText(QCoreApplication::translate("Form_Main", "\341\272\242nh c\305\251( camera sau)", nullptr));
        xera_anh_truoc->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        main_btn_exit->setText(QCoreApplication::translate("Form_Main", "Tho\303\241t", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("Form_Main", "Thao t\303\241c", nullptr));
        xevao_btn_closed->setText(QCoreApplication::translate("Form_Main", "\304\220\303\263ng c\341\273\225ng", nullptr));
        xevao_btn_print->setText(QCoreApplication::translate("Form_Main", "In", nullptr));
        xevao_btn_readagain->setText(QCoreApplication::translate("Form_Main", "\304\220\341\273\215c BKS", nullptr));
        xevao_btn_open->setText(QCoreApplication::translate("Form_Main", "M\341\273\237 c\341\273\225ng", nullptr));
        label_69->setText(QCoreApplication::translate("Form_Main", "BKS m\341\273\233i", nullptr));
        xevao_anh_bks->setText(QCoreApplication::translate("Form_Main", "TextLabel", nullptr));
        menuFile->setTitle(QCoreApplication::translate("Form_Main", "File", nullptr));
        menuC_i_t->setTitle(QCoreApplication::translate("Form_Main", "C\303\240i \304\221\341\272\267t", nullptr));
        menuB_o_c_o->setTitle(QCoreApplication::translate("Form_Main", "B\303\241o c\303\241o", nullptr));
        menuTh_ng_tin->setTitle(QCoreApplication::translate("Form_Main", "Th\303\264ng tin", nullptr));
        menuD_li_u->setTitle(QCoreApplication::translate("Form_Main", "D\341\273\257 li\341\273\207u", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Form_Main: public Ui_Form_Main {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FORM_MAIN_H
